# Permalinks
#
permalink:           /:categories/:year/:month/:day/:title/

# Setup
title:               Farid MUSA
tagline:             Personal WebPage
description:         Coder with an extreme passion for bioinformatics and health informatics.
url:                 http://mmtechslv.github.io
baseurl:             ''
paginate:            5

# Plugins, Tags, Categories and Analytics  
plugins:          
    - jekyll-paginate
    - jekyll-avatar

# About/contact
author:
  name:              Farid MUSA
  url:               https://mmtechslv.github.io
  email:             mmtechslv@gmail.com
